title: RDI Personal
description: A central hub for all things operations
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark
